name: Docker Build
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['1.39', '1.41', '1.42']
        type: [apache]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.version }}/${{ matrix.type }}
          platforms: linux/amd64,linux/arm64 #,linux/arm/v6
          push: true
          tags: gbeine/mediawiki:${{ matrix.version }}
