name: Docker Build
on:
  pull_request:
  push:

defaults:
  run:
    shell: bash

jobs:
  lookup-versions:
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
      - name: Get current versions
        id: versions
        run: |
          echo "versions=$(python -c 'import glob, json; print(json.dumps(glob.glob("1.*")))')" | tee $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest

    needs:
      - lookup-versions
    strategy:
      matrix:
        version: ${{ fromJson(needs.lookup-versions.outputs.versions) }}
        type: [apache]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.version }}/${{ matrix.type }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: gbeine/mediawiki:${{ matrix.version }}
